openapi: 3.0.0
info:
  title: TrAI API Gateway
  version: 1.0.0
servers:
  - url: https://trai-gateway.api.cloud.yandex.net
paths:
  /api/v1/{proxy+}:
    x-yc-apigateway-any-method:
      summary: Proxy all /api/v1 traffic to backend service
      x-yc-apigateway-integration:
        type: http
        url: https://{BACKEND_SERVICE_URL}/api/v1/{proxy}
        method: "*"
        headers:
          X-Forwarded-For: '{requestContext.identity.sourceIp}'
          X-Forwarded-Proto: https
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
